name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias API
        working-directory: api
        run: npm install

      - name: Verificar que Node puede leer server.js
        working-directory: api
        run: node --check server.js

      - name: Construir imagen Docker de la API
        run: docker build -t proyecto-arquitectura-api ./api
